In [2]:
from __future__ import division
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.linalg
import sklearn.linear_model
import sklearn.preprocessing


In [3]:
# Part (c): Read in the data, standardize it
spam = pd.read_table('https://statweb.stanford.edu/~tibs/ElemStatLearn/datasets/spam.data', sep=' ', header=None)
test_indicator = pd.read_table('https://statweb.stanford.edu/~tibs/ElemStatLearn/datasets/spam.traintest', sep=' ',
                               header=None)

x = np.asarray(spam)[:, 0:-1]
y = np.asarray(spam)[:, -1]*2 - 1  # Convert to +/- 1
test_indicator = np.array(test_indicator).T[0]

# Divide the data into train, test sets
x_train = x[test_indicator == 0, :]
x_test = x[test_indicator == 1, :]
y_train = y[test_indicator == 0]
y_test = y[test_indicator == 1]

# Standardize the data. 
scaler = sklearn.preprocessing.StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

# Keep track of the number of samples and dimension of each sample
n_train = len(y_train)
n_test = len(y_test)
d = np.size(x, 1)

In [4]:
spam

0     1     2    3     4     5     6     7     8     9  ...     48  \
0     0.00  0.64  0.64  0.0  0.32  0.00  0.00  0.00  0.00  0.00 ...  0.000   
1     0.21  0.28  0.50  0.0  0.14  0.28  0.21  0.07  0.00  0.94 ...  0.000   
2     0.06  0.00  0.71  0.0  1.23  0.19  0.19  0.12  0.64  0.25 ...  0.010   
3     0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63 ...  0.000   
4     0.00  0.00  0.00  0.0  0.63  0.00  0.31  0.63  0.31  0.63 ...  0.000   
5     0.00  0.00  0.00  0.0  1.85  0.00  0.00  1.85  0.00  0.00 ...  0.000   
6     0.00  0.00  0.00  0.0  1.92  0.00  0.00  0.00  0.00  0.64 ...  0.000   
7     0.00  0.00  0.00  0.0  1.88  0.00  0.00  1.88  0.00  0.00 ...  0.000   
8     0.15  0.00  0.46  0.0  0.61  0.00  0.30  0.00  0.92  0.76 ...  0.000   
9     0.06  0.12  0.77  0.0  0.19  0.32  0.38  0.00  0.06  0.00 ...  0.040   
10    0.00  0.00  0.00  0.0  0.00  0.00  0.96  0.00  0.00  1.92 ...  0.000   
11    0.00  0.00  0.25  0.0  0.38  0.25  0.25  0.00  0.00  0.00 ...  0.022   
12    0.00  0.69  0.34  0.0  0.34  0.00  0.00  0.00  0.00  0.00 ...  0.000   
13    0.00  0.00  0.00  0.0  0.90  0.00  0.90  0.00  0.00  0.90 ...  0.000   
14    0.00  0.00  1.42  0.0  0.71  0.35  0.00  0.35  0.00  0.71 ...  0.000   
15    0.00  0.42  0.42  0.0  1.27  0.00  0.42  0.00  0.00  1.27 ...  0.000   
16    0.00  0.00  0.00  0.0  0.94  0.00  0.00  0.00  0.00  0.00 ...  0.000   
17    0.00  0.00  0.00  0.0  0.00  0.00  0.00  0.00  0.00  0.00 ...  0.000   
18    0.00  0.00  0.55  0.0  1.11  0.00  0.18  0.00  0.00  0.00 ...  0.000   
19    0.00  0.63  0.00  0.0  1.59  0.31  0.00  0.00  0.31  0.00 ...  0.000   
20    0.00  0.00  0.00  0.0  0.00  0.00  0.00  0.00  0.00  0.00 ...  0.000   
21    0.05  0.07  0.10  0.0  0.76  0.05  0.15  0.02  0.55  0.00 ...  0.042   
22    0.00  0.00  0.00  0.0  2.94  0.00  0.00  0.00  0.00  0.00 ...  0.404   
23    0.00  0.00  0.00  0.0  1.16  0.00  0.00  0.00  0.00  0.00 ...  0.000   
24    0.00  0.00  0.00  0.0  0.00  0.00  0.00  0.00  0.00  0.00 ...  0.000   
25    0.05  0.07  0.10  0.0  0.76  0.05  0.15  0.02  0.55  0.00 ...  0.042   
26    0.00  0.00  0.00  0.0  0.00  0.00  0.00  0.00  0.00  0.00 ...  0.000   
27    0.00  0.00  0.00  0.0  0.00  0.00  1.66  0.00  0.00  0.00 ...  0.000   
28    0.00  0.00  0.00  0.0  0.00  0.00  0.00  0.00  0.00  0.00 ...  0.000   
29    0.00  0.00  0.00  0.0  0.65  0.00  0.65  0.00  0.00  0.00 ...  0.000   
...    ...   ...   ...  ...   ...   ...   ...   ...   ...   ... ...    ...   
4571  0.00  0.00  0.46  0.0  0.23  0.23  0.00  0.00  0.00  0.00 ...  0.000   
4572  0.00  0.00  0.00  0.0  0.00  0.00  0.00  0.00  0.00  0.00 ...  0.000   
4573  0.00  0.00  0.18  0.0  0.18  0.18  0.00  0.00  0.00  0.00 ...  0.033   
4574  0.29  0.00  0.29  0.0  0.00  0.00  0.00  0.00  0.00  0.29 ...  0.000   
4575  0.00  0.00  0.00  0.0  0.00  0.00  0.00  0.00  0.00  1.38 ...  0.000   
4576  0.00  0.00  0.00  0.0  0.00  0.00  0.00  0.00  0.00  0.00 ...  0.000   
4577  0.00  0.00  1.20  0.0  0.00  0.00  0.00  0.00  0.00  0.00 ...  0.000   
4578  0.00  0.00  0.40  0.0  0.00  0.00  0.00  0.00  0.00  0.00 ...  0.000   
4579  0.27  0.05  0.10  0.0  0.00  0.00  0.00  0.00  0.00  0.00 ...  0.607   
4580  0.00  0.00  0.00  0.0  0.00  0.00  0.00  0.00  0.00  0.00 ...  0.000   
4581  0.00  0.00  0.00  0.0  0.00  0.51  0.00  0.00  0.00  0.00 ...  0.000   
4582  0.00  0.00  0.00  0.0  0.00  0.00  0.00  0.00  0.00  0.00 ...  0.000   
4583  0.00  0.00  1.23  0.0  0.00  0.00  0.00  0.00  0.00  0.00 ...  0.000   
4584  0.00  0.00  0.45  0.0  0.00  0.22  0.00  0.00  0.00  0.00 ...  0.000   
4585  0.00  0.00  0.00  0.0  0.00  0.00  0.00  0.00  0.00  0.00 ...  0.000   
4586  0.00  0.00  0.00  0.0  0.36  0.00  0.00  0.00  0.00  0.00 ...  0.000   
4587  0.00  0.00  0.00  0.0  0.00  0.00  0.00  0.00  0.00  0.00 ...  0.000   
4588  0.00  0.00  3.03  0.0  0.00  0.00  0.00  0.00  0.00  0.00 ...  0.000   
4589  0.00  0.00  0.00  0.0  0.54  0.00  0.00  0.00  0.00  0.00 ...  0.000   
4590  0.00  0.00  0.00  0.0  0

In [5]:
test_indicator

array([1, 0, 1, ..., 0, 0, 0], dtype=int64)

In [6]:
x

array([[  0.00000000e+00,   6.40000000e-01,   6.40000000e-01, ...,
          3.75600000e+00,   6.10000000e+01,   2.78000000e+02],
       [  2.10000000e-01,   2.80000000e-01,   5.00000000e-01, ...,
          5.11400000e+00,   1.01000000e+02,   1.02800000e+03],
       [  6.00000000e-02,   0.00000000e+00,   7.10000000e-01, ...,
          9.82100000e+00,   4.85000000e+02,   2.25900000e+03],
       ..., 
       [  3.00000000e-01,   0.00000000e+00,   3.00000000e-01, ...,
          1.40400000e+00,   6.00000000e+00,   1.18000000e+02],
       [  9.60000000e-01,   0.00000000e+00,   0.00000000e+00, ...,
          1.14700000e+00,   5.00000000e+00,   7.80000000e+01],
       [  0.00000000e+00,   0.00000000e+00,   6.50000000e-01, ...,
          1.25000000e+00,   5.00000000e+00,   4.00000000e+01]])

In [7]:
y

array([ 1.,  1.,  1., ..., -1., -1., -1.])

In [8]:
test_indicator

array([1, 0, 1, ..., 0, 0, 0], dtype=int64)

In [ ]:




# Part (d): Function for the gradient
def computegrad(beta, lambduh, x=x_train, y=y_train):
    yx = y[:, np.newaxis]*x
    denom = 1+np.exp(-yx.dot(beta))
    grad = 1/len(y)*np.sum(-yx*np.exp(-yx.dot(beta[:, np.newaxis]))/denom[:, np.newaxis], axis=0) + 2*lambduh*beta
    return grad


# Part (e): Backtracking line search (and objective function)
def objective(beta, lambduh, x=x_train, y=y_train):
    return 1/len(y) * np.sum(np.log(1 + np.exp(-y*x.dot(beta)))) + lambduh * np.linalg.norm(beta)**2


def bt_line_search(beta, lambduh, eta=1, alpha=0.5, betaparam=0.8,
                   maxiter=100, x=x_train, y=y_train):
    grad_beta = computegrad(beta, lambduh, x=x, y=y)
    norm_grad_beta = np.linalg.norm(grad_beta)
    found_eta = 0
    iter = 0
    while found_eta == 0 and iter < maxiter:
        if objective(beta - eta * grad_beta, lambduh, x=x, y=y) < objective(beta, lambduh, x=x, y=y) \
                - alpha * eta * norm_grad_beta ** 2:
            found_eta = 1
        elif iter == maxiter:
            raise ('Max number of iterations of backtracking'
                   ' line search reached')
        else:
            eta *= betaparam
            iter += 1
    return eta


# Part (f): Gradient descent algorithm
def graddescent(beta_init, lambduh, eta_init, maxiter, x=x_train, y=y_train):
    beta = beta_init
    grad_beta = computegrad(beta, lambduh, x=x, y=y)
    beta_vals = beta
    iter = 0
    while iter < maxiter:
        eta = bt_line_search(beta, lambduh, eta=eta_init, x=x, y=y)
        beta = beta - eta*grad_beta
        # Store all of the places we step to
        beta_vals = np.vstack((beta_vals, beta))
        grad_beta = computegrad(beta, lambduh, x=x, y=y)
        iter += 1
        if iter % 100 == 0:
            print('Gradient descent iteration', iter)
    return beta_vals


# Part (g): Fast gradient algorithm
def fastgradalgo(beta_init, theta_init, lambduh, eta_init, maxiter, x=x_train, y=y_train):
    beta = beta_init
    theta = theta_init
    grad_theta = computegrad(theta, lambduh, x=x, y=y)
    theta_vals = theta
    iter = 0
    while iter < maxiter:
        eta = bt_line_search(theta, lambduh, eta=eta_init, x=x, y=y)
        beta_new = theta - eta*grad_theta
        theta = beta_new + iter/(iter+3)*(beta_new-beta)
        # Store all of the places we step to
        theta_vals = np.vstack((theta_vals, theta))
        grad_theta = computegrad(theta, lambduh, x=x, y=y)
        beta = beta_new
        iter += 1
        if iter % 100 == 0:
            print('Fast gradient iteration', iter)
    return theta_vals


# Part (h)
def objective_plot(betas_gd, betas_fg, lambduh, x=x_train, y=y_train, save_file=''):
    num_points = np.size(betas_gd, 0)
    objs_gd = np.zeros(num_points)
    objs_fg = np.zeros(num_points)
    for i in range(0, num_points):
        objs_gd[i] = objective(betas_gd[i, :], lambduh, x=x, y=y)
        objs_fg[i] = objective(betas_fg[i, :], lambduh, x=x, y=y)
    fig, ax = plt.subplots()
    ax.plot(range(1, num_points + 1), objs_gd, label='gradient descent')
    ax.plot(range(1, num_points + 1), objs_fg, c='red', label='fast gradient')
    plt.xlabel('Iteration')
    plt.ylabel('Objective value')
    plt.title('Objective value vs. iteration when lambda='+str(lambduh))
    ax.legend(loc='upper right')
    if not save_file:
        plt.show()
    else:
        plt.savefig(save_file)


lambduh = 0.1
beta_init = np.zeros(d)
theta_init = np.zeros(d)
# See slide 28 in the lecture 3 slides for how to initialize the step size
eta_init = 1/(scipy.linalg.eigh(1/len(y_train)*x_train.T.dot(x_train), eigvals=(d-1, d-1), eigvals_only=True)[0]+lambduh)
maxiter = 1000
betas_grad = graddescent(beta_init, lambduh, eta_init, maxiter)
betas_fastgrad = fastgradalgo(beta_init, theta_init, lambduh, eta_init, maxiter)
objective_plot(betas_grad, betas_fastgrad, lambduh, save_file='hw3_q1_part_h_output.png')


# Part (i): Compare to scikit-learn
lr = sklearn.linear_model.LogisticRegression(penalty='l2', C=1/(2*lambduh*n_train), fit_intercept=False, tol=10e-8, max_iter=1000)
lr.fit(x_train, y_train)
print(lr.coef_)
print(betas_fastgrad[-1, :])

print(objective(betas_fastgrad[-1, :], lambduh))
print(objective(lr.coef_.flatten(), lambduh))


# Part (j): Run cross-validation to find lambda. Plot the objective values and misclassification errors
def compute_misclassification_error(beta_opt, x, y):
    y_pred = 1/(1+np.exp(-x.dot(beta_opt))) > 0.5
    y_pred = y_pred*2 - 1  # Convert to +/- 1
    return np.mean(y_pred != y)


def plot_misclassification_error(betas_grad, betas_fastgrad, x, y, save_file='', title=''):
    niter = np.size(betas_grad, 0)
    error_grad = np.zeros(niter)
    error_fastgrad = np.zeros(niter)
    for i in range(niter):
        error_grad[i] = compute_misclassification_error(betas_grad[i, :], x, y)
        error_fastgrad[i] = compute_misclassification_error(betas_fastgrad[i, :], x, y)
    fig, ax = plt.subplots()
    ax.plot(range(1, niter + 1), error_grad, label='gradient descent')
    ax.plot(range(1, niter + 1), error_fastgrad, c='red', label='fast gradient')
    plt.xlabel('Iteration')
    plt.ylabel('Misclassification error')
    if title:
        plt.title(title)
    ax.legend(loc='upper right')
    if not save_file:
        plt.show()
    else:
        plt.savefig(save_file)

lr_cv = sklearn.linear_model.LogisticRegressionCV(penalty='l2', fit_intercept=False, tol=10e-8, max_iter=1000)
lr_cv.fit(x_train, y_train)
optimal_lambda = lr_cv.C_[0]
print('Optimal lambda=', optimal_lambda)

betas_grad = graddescent(beta_init, optimal_lambda, eta_init, maxiter)
betas_fastgrad = fastgradalgo(beta_init, theta_init, optimal_lambda, eta_init, maxiter)

objective_plot(betas_grad, betas_fastgrad, optimal_lambda, save_file='hw3_q1_part_j_output1.png')
plot_misclassification_error(betas_grad, betas_fastgrad, x_train, y_train, save_file='hw3_q1_part_j_output2.png',
                             title='Training set misclassification error')
plot_misclassification_error(betas_grad, betas_fastgrad, x_test, y_test, save_file='hw3_q1_part_j_output3.png',
                             title='Test set misclassification error')








